// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwklkamxdlggpusdiohp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13a2xrYW14ZGxnZ3B1c2Rpb2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDExNTAsImV4cCI6MjA3MTk3NzE1MH0.Mn7ro4ry2YKexcMZ21_CJ3JC2XU5tXH4EvkaxUgurFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});